install:
  grub-entry-name: Tangent

  partitions:
    persistent:
      label: COS_PERSISTENT
      fs: ext4
      encryption:
        name: persistent
        key_slots:
          - slot: 0
            passphrase: asd123

# configuration used for the 'mount' command
mount:
  read-kernel-cmdline: true # read and parse /proc/cmdline for arguments
  root: /sysroot
