name: "Rootfs Layout Settings"
stages:
  rootfs:
    - name: "Layout configuration"
      environment_file: /run/cos/cos-layout.env
      environment:
        VOLUMES: "LABEL=COS_OEM:/oem LABEL=COS_PERSISTENT:/usr/local"
        OVERLAY: "tmpfs:25%"
        RW_PATHS: "/var /etc /srv"
        PERSISTENT_STATE_PATHS: >-
          /etc/systemd
          /etc/ssh
          /etc/iscsi 
          /home
          /opt
          /root
          /usr/libexec
          /var/log
          /var/lib/NetworkManager
        PERSISTENT_STATE_BIND: "true"
