name: "Rootfs Layout Settings"
stages:
  rootfs:
    - name: "Layout configuration"
      environment_file: /run/cos/cos-layout.env
      environment:
        OVERLAY: "tmpfs:25%"
        RW_PATHS: "/var /etc /srv"
        PERSISTENT_STATE_PATHS: >-
          /etc/systemd
          /etc/ssh
          /home
          /opt
          /root
          /usr/libexec
          /var/log
          /var/lib/NetworkManager
