stages:
  fs:
    - if: '[ ! -f "/run/elemental/recovery_mode" ]'
      name: "Post-install settings"
      hostname: "tangent"
    - if: '[ -f "/run/elemental/recovery_mode" ]'
      name: "Recovery settings"
      hostname: "tangent-recovery"
