name: Build ISO
on:
  workflow_dispatch:
  pull_request:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest
    container:
      image: quay.io/costoolkit/elemental-cli:latest
    steps:
      - name: Install tar
        run: zypper install -y tar
      - name: Checkout code
        uses: actions/checkout@v3.1.0
      - name: Build ISO
        uses: frelon/actions/elemental/build-iso@main
        with:
          system-uri: frallan/tangent:v0.1.0
          output-dir: build
      - name: Archive ISO
        uses: actions/upload-artifact@v3
        with:
          name: tangent-x86_64
          path: build/*
