name: Build ISO
on:
  workflow_dispatch:
  pull_request:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3.1.0
      - name: Build ISO
        uses: frelon/actions/elemental/build-iso@main
        with:
          system-uri: frallan/tangent:v0.1.0

